### ISSUE TITLE
REPORTE DE PRÁCTICA1

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/practica-architect-IsaHuerta23#1]
REPORTE DE PRÁCTICA #1

[Reporte de Práctica1.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-IsaHuerta23/files/7163421/Reporte.de.Practica1.pdf) 

[Diagrama UMG.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-IsaHuerta23/files/7163563/Diagrama.UMG.pdf)

**Comment by ArturoAngonJose** [comment]
calificación: 20/ 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
